### ISSUE TITLE
It has errors. Does not work out of the box

### ISSUE THREAD

**Issue by teacii** [akmittal/angular2-datepicker#1]
ERROR in ./src/my-date-picker/my-date-picker.component.ts
(2,40): error TS2305: Module '"D:/wamp64/www/a2dtpkrmaster/node_modules/@angular/common/index"' has no exported member 'NgModel'.

ERROR in ./src/my-date-picker/my-date-picker.component.ts
(11,5): error TS2345: Argument of type '{ selector: string; directives: (typeof NgIf | typeof NgFor | typeof NgClass | typeof NgStyle)[];...' is not assignable to parameter of type 'Component'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'Component'.

ERROR in ./src/sample-date-app/sample-date-app.component.ts
(10,5): error TS2345: Argument of type '{ selector: string; directives: typeof MyDatePicker[]; styles: string[]; template: string; }' is not assignable to parameter of type 'Component'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'Component'.

ERROR in ./src/main.ts
(1,9): error TS2305: Module '"D:/wamp64/www/a2dtpkrmaster/node_modules/@angular/core/index"' has no exported member 'provide'.

ERROR in ./src/main.ts
(2,9): error TS2305: Module '"D:/wamp64/www/a2dtpkrmaster/node_modules/@angular/platform-browser-dynamic/index"' has no exported member 'bootstrap'.

**Comment by akmittal** [comment]
Pushed a new update. Everything should be working fine now.

**Comment by teacii** [comment]
Thanks for the update.
I downloaded and did npm install and npm start. Still got error 
ERROR in ./src/main.ts
Module build failed: A file specified in tsconfig.json could not be found: D:\wamp64\www\angular2-datepicker-master\typings\browser.d.ts

**Comment by akmittal** [comment]
Removed that part from tsconfig.json. Should work fine without it.

**Comment by teacii** [comment]
Thanks again for the fast update.

The demo worked out of the box now. There were some errors though:

WARNING in ./~/ng2-bootstrap/bundles/ng2-bootstrap.umd.js
Critical dependencies:
1:3743-3750 require function is used in a way in which dependencies cannot be statically extracted
1:3789-3796 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/ng2-bootstrap/bundles/ng2-bootstrap.umd.js 1:3743-3750 1:3789-3796

WARNING in ./~/ng2-bootstrap/bundles/ng2-bootstrap.umd.min.js
Critical dependencies:
1:3743-3750 require function is used in a way in which dependencies cannot be statically extracted
1:3789-3796 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/ng2-bootstrap/bundles/ng2-bootstrap.umd.min.js 1:3743-3750 1:3789-3796
